[package]
name = "println"
version = "0.1.0"
authors = ["Karlkim Suwamongkol <contact@karlk.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-money = "0.4.1"
colored = "2.0.0"